repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: 'v1.0.1' # Use the sha or tag you want to point at
    hooks:
      - id: go-fmt-import
      - id: golangci-lint # requires github.com/golangci/golangci-lint
