package vsys

import "fmt"

type FuncIdx uint16

func (f FuncIdx) Serialize() Bytes {
	return PackUInt16(uint16(f))
}

func (f FuncIdx) String() string {
	return fmt.Sprintf("%T(%d)", f, f)
}

const (
	FUNC_IDX_NFT_SUPERSEDE = FuncIdx(iota)
	FUNC_IDX_NFT_ISSUE
	FUNC_IDX_NFT_SEND
	FUNC_IDX_NFT_TRANSFER
	FUNC_IDX_NFT_DEPOSIT
	FUNC_IDX_NFT_WITHDRAW
)

const (
	FUNC_IDX_ATOMIC_SWAP_LOCK = FuncIdx(iota)
	FUNC_IDX_ATOMIC_SWAP_SOLVE_PUZZLE
	FUNC_IDX_ATOMIC_SWAP_EXPIRE_WITHDRAW
)

const (
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_SUPERSEDE = FuncIdx(iota)
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_ISSUE
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_DESTROY
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_SEND
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_TRANSFER
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_DEPOSIT
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_WITHDRAW
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_TOTAL_SUPPLY
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_MAX_SUPPLY
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_BALANCE_OF
	FUNC_IDX_TOK_CTRT_WITHOUT_SPLIT_GET_ISSUER
)

const (
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_SUPERSEDE = FuncIdx(iota)
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_ISSUE
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_DESTROY
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_SPLIT
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_SEND
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_TRANSFER
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_DEPOSIT
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_WITHDRAW
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_TOTAL_SUPPLY
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_MAX_SUPPLY
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_BALANCE_OF
	FUNC_IDX_TOK_CTRT_WITH_SPLIT_GET_ISSUER
)

const (
	FUNC_IDX_TOK_CTRT_V2_SUPERSEDE = FuncIdx(iota)
	FUNC_IDX_TOK_CTRT_V2_ISSUE
	FUNC_IDX_TOK_CTRT_V2_DESTROY
	FUNC_IDX_TOK_CTRT_V2_UPDATE_LIST
	FUNC_IDX_TOK_CTRT_V2_SEND
	FUNC_IDX_TOK_CTRT_V2_TRANSFER
	FUNC_IDX_TOK_CTRT_V2_DEPOSIT
	FUNC_IDX_TOK_CTRT_V2_WITHDRAW
	FUNC_IDX_TOK_CTRT_V2_TOTAL_SUPPLY
	FUNC_IDX_TOK_CTRT_V2_MAX_SUPPLY
	FUNC_IDX_TOK_CTRT_V2_BALANCE_OF
	FUNC_IDX_TOK_CTRT_V2_GET_ISSUER
)
