package vsys

import "fmt"

type StateMapIdx uint8

func (s StateMapIdx) Serialize() Bytes {
	return PackUInt8(uint8(s))
}

func (s StateMapIdx) String() string {
	return fmt.Sprintf("%T(%d)", s, s)
}

// Constants for Atomic Swap Contract state map indexes.
const (
	STATE_MAP_IDX_ATOMIC_SWAP_CONTRACT_BALANCE = StateMapIdx(iota)
	STATE_MAP_IDX_ATOMIC_SWAP_OWNER
	STATE_MAP_IDX_ATOMIC_SWAP_RECIPIENT
	STATE_MAP_IDX_ATOMIC_SWAP_PUZZLE
	STATE_MAP_IDX_ATOMIC_SWAP_AMOUNT
	STATE_MAP_IDX_ATOMIC_SWAP_EXPIRED_TIME
	STATE_MAP_IDX_ATOMIC_SWAP_STATUS
)

const (
	STATE_MAP_IDX_TOK_CTRT_V2_IS_IN_LIST = StateMapIdx(iota)
)

const (
	STATE_MAP_IDX_V_ESCROW_CONTRACT_BALANCE = StateMapIdx(iota)
	STATE_MAP_IDX_V_ESCROW_ORDER_PAYER
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT
	STATE_MAP_IDX_V_ESCROW_ORDER_AMOUNT
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT_DEPOSIT
	STATE_MAP_IDX_V_ESCROW_ORDER_JUDGE_DEPOSIT
	STATE_MAP_IDX_V_ESCROW_ORDER_FEE
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT_AMOUNT
	STATE_MAP_IDX_V_ESCROW_ORDER_REFUND
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT_REFUND
	STATE_MAP_IDX_V_ESCROW_ORDER_EXPIRATION_TIME
	STATE_MAP_IDX_V_ESCROW_ORDER_STATUS
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT_DEPOSIT_STATUS
	STATE_MAP_IDX_V_ESCROW_ORDER_JUDGE_DEPOSIT_STATUS
	STATE_MAP_IDX_V_ESCROW_ORDER_SUBMIT_STATUS
	STATE_MAP_IDX_V_ESCROW_ORDER_JUDGE_STATUS
	STATE_MAP_IDX_V_ESCROW_ORDER_RECIPIENT_LOCKED_AMOUNT
	STATE_MAP_IDX_V_ESCROW_ORDER_JUDGE_LOCKED_AMOUNT
)
